name: Terraform AWS-Azure Hybrid
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    environment: hybrid-aws-azure-demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - name: Validate identity
        run: aws sts get-caller-identity

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        working-directory: ./projects/03-AWS–Azure-Hybrid-Cloud-with-OIDC
        env:
          TF_VAR_runner_github_repo: terraform
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUB_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ./projects/03-AWS–Azure-Hybrid-Cloud-with-OIDC
        env:
          TF_VAR_runner_github_repo: terraform
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUB_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./projects/03-AWS–Azure-Hybrid-Cloud-with-OIDC
        env:
          TF_VAR_runner_github_repo: terraform
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUB_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
        run: terraform apply -auto-approve